### ISSUE TITLE
Adding section (open/closed) indicator to headers

### ISSUE THREAD

**Issue by danielsalare** [simonbromberg/SBAccordionViewController#1]
I have managed to add a custom cell with no problem, but I want to add an accessory UIImage to indicate if the section is opened or closed, any ideas on how I can implement this?

**Comment by simonbromberg** [comment]
Just modify cellForRowAtIndexPath when indexPath.row == expandedRow (i.e. header row), and update the image accordingly

**Comment by danielsalare** [comment]
I'm trying to add the condition cellForRowAtIndexPath but couldn't make it work, also tried on didselectRowAtIndexPath and nothing :S. 

If you have any other options or if this is something planned for this repo please tell. 

Thanks
